from conformed_dimensions.extract.conformed_extract import (
    EXTRACT_HRM_EMPLOYEE_QUERY,
    EXTRACT_ERP_EMPLOYEE_QUERY
)
from conformed_dimensions.transform.conformed_transform import trans_employee

# Note: dim_date already generated by script → not in registry
# Note: dim_employee needs special handling → merged from HRM + ERP
# So registry is not used directly for dim_employee
# Instead main_conformed.py handles the merge logic

ETL_Conformed_Registry = {
    "dim_employee": {
        "hrm_query":      EXTRACT_HRM_EMPLOYEE_QUERY,
        "erp_query":      EXTRACT_ERP_EMPLOYEE_QUERY,
        "transform_func": trans_employee,
        "insert_query": """
            INSERT INTO public.dim_employee (
                employee_id, name, gender, nationality,
                marital_status, birth_date, hiring_date,
                getting_position_date, contract_type, contract_end_date,
                site_name, supervisor_id, supervisor_key, is_active,
                position_name, position_type, position_level,
                team_name, team_description, education, school,
                previous_position, changing_position,
                resign_request_date, resign_leave_date, approve_by, source_system
            )
            VALUES (
                :employee_id, :name, :gender, :nationality,
                :marital_status, :birth_date, :hiring_date,
                :getting_position_date, :contract_type, :contract_end_date,
                :site_name, :supervisor_id, :supervisor_key, :is_active,
                :position_name, :position_type, :position_level,
                :team_name, :team_description, :education, :school,
                :previous_position, :changing_position,
                :resign_request_date, :resign_leave_date, :approve_by, :source_system
            )
            ON CONFLICT (employee_id, source_system) DO NOTHING;
        """
    }
}